name: Update MDC File

on:
  push:
    paths:
      - 'README.md'
    branches:
      - main

jobs:
  update-mdc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if README.md has been modified
        id: check
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "README.md"; then
            echo "README_CHANGED=true" >> $GITHUB_ENV
          else
            echo "README_CHANGED=false" >> $GITHUB_ENV
          fi

      - name: Add testing section to rule.mdc
        if: env.README_CHANGED == 'true'
        run: |
          # テスト方法のセクションがREADME.mdにあれば、rule.mdcに追加または更新
          TEST_SECTION=$(sed -n '/^## テスト方法/,/^##/p' README.md | sed '$d')
          
          if [ -n "$TEST_SECTION" ]; then
            # rule.mdcファイルが存在するか確認
            if [ -f "rule.mdc" ]; then
              # rule.mdcにテストセクションがあるか確認
              if grep -q "^## テスト方法" rule.mdc; then
                # 既存のテストセクションを削除
                sed -i '/^## テスト方法/,/^##/{ /^##/!d; }' rule.mdc
                # 最後のセクションの前にテストセクションを追加
                sed -i '$a\' rule.mdc
                echo "$TEST_SECTION" >> rule.mdc
              else
                # テストセクションがなければ、ファイルの最後に追加
                echo "" >> rule.mdc
                echo "$TEST_SECTION" >> rule.mdc
              fi
            else
              # rule.mdcが存在しなければ、README.mdの内容をコピー
              cp README.md rule.mdc
            fi
          fi

      - name: Commit and push changes
        if: env.README_CHANGED == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add rule.mdc
          git commit -m "Update rule.mdc from README.md" || echo "No changes to commit"
          git push 